security:
    encoders:
        Taskboxx\FrontendBundle\Entity\User: md5

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        main:
            entity: { class: TaskBoxxFrontendBundle:User, property: username }
        #in_memory:
        #    users:
        #        user:  { password: userpass, roles: [ 'ROLE_USER' ] }
        #        admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        profiler:
            pattern:  ^/_profiler
            security: false

        wdt:
            pattern:  ^/_wdt
            security: false
            
        login:
            pattern:  ^/login$
            security: false
            
        main:
            pattern:      /.*
            form_login:   
                check_path: /login_check
                login_path: /login
                success_handler: login_success
            logout:       
                path:   /logout
                target: /
                invalidate_session: true
        

    access_control:
        - { path: /.*, roles: ROLE_USER }
        - { path: /admin, roles: ROLE_ADMIN }
