homepage:
    pattern:  /
    defaults: { _controller: ShiftUpTaskBoxxBundle:Board:index }
    
taskboxx_account_show:
    pattern: /account/show
    defaults: { _controller: ShiftUpTaskBoxxBundle:Account:show }

taskboxx_admin_index:
    pattern: /admin
    defaults: { _controller: ShiftUpTaskBoxxBundle:Admin:index }

taskboxx_login:
    pattern: /login
    defaults: { _controller: ShiftUpTaskBoxxBundle:Security:login }

taskboxx_logout:
    pattern: /logout
    defaults: { _controller: ShiftUpTaskBoxxBundle:Security:logout }

taskboxx_project_list:
    pattern: /projects
    defaults: { _controller: ShiftUpTaskBoxxBundle:Project:list }

# Project
taskboxx_project_board:
    pattern: /{project}/board
    defaults: { _controller: ShiftUpTaskBoxxBundle:Board:index }

taskboxx_activity:
    pattern: /{project}/activity
    defaults: { _controller: ShiftUpTaskBoxxBundle:Activity:index }

taskboxx_roadmap:
    pattern: /{project}/roadmap
    defaults: { _controller: ShiftUpTaskBoxxBundle:Roadmap:index }

taskboxx_tasks:
    pattern: /{project}/tasks
    defaults: { _controller: ShiftUpTaskBoxxBundle:Task:index }

taskboxx_new_issue:
    pattern: /{project}/task/new
    defaults: { _controller: ShiftUpTaskBoxxBundle:Task:new }
    
taskboxx_settings:
    pattern: /{project}/settings
    defaults: { _controller: ShiftUpTaskBoxxBundle:Settings:index }


_security_check:
    pattern: /login_check
    defaults: { _controller: ShiftUpTaskBoxxBundle:Security:securityCheck }
